name: diff_match_patch
version: 0.1.0
description: >
  The Diff Match and Patch libraries offer robust algorithms to perform the
  operations required for synchronizing plain text.
authors:
- Boris Kaul <localvoid@gmail.com>
- Neil Fraser <neil.fraser@gmail.com>
description: A pub package
homepage: http://github.com/localvoid/diff-match-patch
dev_dependencies:
  unittest: any
